name = "nutriscan"
main = "worker.py"
compatibility_date = "2023-01-01"

[vars]
STRIPE_SECRET_KEY = "your_stripe_secret"
STRIPE_PUBLISHABLE_KEY = "your_stripe_publishable"
OPENAI_API_KEY = "your_openai_key"
DATABASE_URL = "sqlite:///nutriscan.db"
